#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MatheQuiz.Resource", IsApplication=true)]

namespace MatheQuiz
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int alignmentMode = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int columnCount = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int columnOrderPreserved = 2130771974;
			
			// aapt resource value: 0x7f010015
			public const int font = 2130771989;
			
			// aapt resource value: 0x7f01000e
			public const int fontProviderAuthority = 2130771982;
			
			// aapt resource value: 0x7f010011
			public const int fontProviderCerts = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int fontProviderFetchStrategy = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int fontProviderFetchTimeout = 2130771987;
			
			// aapt resource value: 0x7f01000f
			public const int fontProviderPackage = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int fontProviderQuery = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int fontStyle = 2130771988;
			
			// aapt resource value: 0x7f010016
			public const int fontWeight = 2130771990;
			
			// aapt resource value: 0x7f01000a
			public const int layout_column = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int layout_columnSpan = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int layout_columnWeight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int layout_gravity = 2130771981;
			
			// aapt resource value: 0x7f010007
			public const int layout_row = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int layout_rowSpan = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int layout_rowWeight = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int orientation = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int rowCount = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int rowOrderPreserved = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int useDefaultMargins = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070000
			public const int abc_action_bar_embed_tabs = 2131165184;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int notification_action_color_filter = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int notification_icon_bg_color = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int ripple_material_light = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int secondary_text_default_material_light = 2131230723;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050005
			public const int compat_button_inset_horizontal_material = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int compat_button_inset_vertical_material = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int compat_button_padding_horizontal_material = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int compat_button_padding_vertical_material = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int compat_control_corner_material = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int default_gap = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int notification_action_icon_size = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int notification_action_text_size = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int notification_big_circle_margin = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int notification_content_margin_start = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int notification_large_icon_height = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int notification_large_icon_width = 2131034126;
			
			// aapt resource value: 0x7f050003
			public const int notification_main_column_padding_top = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int notification_media_narrow_margin = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int notification_right_icon_size = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int notification_right_side_padding_top = 2131034113;
			
			// aapt resource value: 0x7f050010
			public const int notification_small_icon_background_padding = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int notification_small_icon_size_as_large = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int notification_subtext_size = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int notification_top_pad = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int notification_top_pad_large_text = 2131034132;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int MatheQuiz = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_action_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_low_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_bg_normal_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_icon_background = 2130837512;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int notification_template_icon_low_bg = 2130837516;
			
			// aapt resource value: 0x7f020009
			public const int notification_tile_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notify_panel_notification_icon_bg = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0026
			public const int action_container = 2131361830;
			
			// aapt resource value: 0x7f0a0032
			public const int action_divider = 2131361842;
			
			// aapt resource value: 0x7f0a0027
			public const int action_image = 2131361831;
			
			// aapt resource value: 0x7f0a0028
			public const int action_text = 2131361832;
			
			// aapt resource value: 0x7f0a0033
			public const int actions = 2131361843;
			
			// aapt resource value: 0x7f0a0007
			public const int alignBounds = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int alignMargins = 2131361800;
			
			// aapt resource value: 0x7f0a0021
			public const int answer1 = 2131361825;
			
			// aapt resource value: 0x7f0a0022
			public const int answer2 = 2131361826;
			
			// aapt resource value: 0x7f0a0023
			public const int answer3 = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public const int answer4 = 2131361828;
			
			// aapt resource value: 0x7f0a0017
			public const int async = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int blocking = 2131361816;
			
			// aapt resource value: 0x7f0a0009
			public const int bottom = 2131361801;
			
			// aapt resource value: 0x7f0a0036
			public const int btnStart = 2131361846;
			
			// aapt resource value: 0x7f0a000a
			public const int center = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int center_horizontal = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int center_vertical = 2131361804;
			
			// aapt resource value: 0x7f0a0031
			public const int chronometer = 2131361841;
			
			// aapt resource value: 0x7f0a000d
			public const int clip_horizontal = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int clip_vertical = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int end = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int fill = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int fill_horizontal = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int fill_vertical = 2131361810;
			
			// aapt resource value: 0x7f0a001c
			public const int finalScore = 2131361820;
			
			// aapt resource value: 0x7f0a0019
			public const int forever = 2131361817;
			
			// aapt resource value: 0x7f0a001d
			public const int goBack = 2131361821;
			
			// aapt resource value: 0x7f0a0005
			public const int horizontal = 2131361797;
			
			// aapt resource value: 0x7f0a002a
			public const int icon = 2131361834;
			
			// aapt resource value: 0x7f0a0034
			public const int icon_group = 2131361844;
			
			// aapt resource value: 0x7f0a0035
			public const int imageView1 = 2131361845;
			
			// aapt resource value: 0x7f0a002d
			public const int info = 2131361837;
			
			// aapt resource value: 0x7f0a001a
			public const int italic = 2131361818;
			
			// aapt resource value: 0x7f0a0013
			public const int left = 2131361811;
			
			// aapt resource value: 0x7f0a0000
			public const int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a001b
			public const int normal = 2131361819;
			
			// aapt resource value: 0x7f0a002f
			public const int notification_background = 2131361839;
			
			// aapt resource value: 0x7f0a002b
			public const int notification_main_column = 2131361835;
			
			// aapt resource value: 0x7f0a0029
			public const int notification_main_column_container = 2131361833;
			
			// aapt resource value: 0x7f0a001e
			public const int questionNumber = 2131361822;
			
			// aapt resource value: 0x7f0a0020
			public const int question_text = 2131361824;
			
			// aapt resource value: 0x7f0a0014
			public const int right = 2131361812;
			
			// aapt resource value: 0x7f0a002e
			public const int right_icon = 2131361838;
			
			// aapt resource value: 0x7f0a002c
			public const int right_side = 2131361836;
			
			// aapt resource value: 0x7f0a0015
			public const int start = 2131361813;
			
			// aapt resource value: 0x7f0a0002
			public const int text = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int text2 = 2131361795;
			
			// aapt resource value: 0x7f0a0030
			public const int time = 2131361840;
			
			// aapt resource value: 0x7f0a0025
			public const int timer = 2131361829;
			
			// aapt resource value: 0x7f0a0004
			public const int title = 2131361796;
			
			// aapt resource value: 0x7f0a0016
			public const int top = 2131361814;
			
			// aapt resource value: 0x7f0a0006
			public const int vertical = 2131361798;
			
			// aapt resource value: 0x7f0a001f
			public const int view_points = 2131361823;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0b0000
			public const int status_bar_notification_info_maxnum = 2131427328;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EndScore = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_action = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_action_tombstone = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_template_custom_big = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_template_icon_group = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_part_chronometer = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_template_part_time = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int StartScreen = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int AnswerRight = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int AnswerWrong = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int BackgroundEnd = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int BackgroundStart = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int button_click1 = 2130968580;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int status_bar_notification_info_overflow = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int TextAppearance_Compat_Notification = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int TextAppearance_Compat_Notification_Info = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int TextAppearance_Compat_Notification_Line2 = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int TextAppearance_Compat_Notification_Time = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int TextAppearance_Compat_Notification_Title = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int Widget_Compat_NotificationActionContainer = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int Widget_Compat_NotificationActionText = 2131296261;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			public static int[] GridLayout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 4
			public const int GridLayout_alignmentMode = 4;
			
			// aapt resource value: 2
			public const int GridLayout_columnCount = 2;
			
			// aapt resource value: 6
			public const int GridLayout_columnOrderPreserved = 6;
			
			// aapt resource value: 0
			public const int GridLayout_orientation = 0;
			
			// aapt resource value: 1
			public const int GridLayout_rowCount = 1;
			
			// aapt resource value: 5
			public const int GridLayout_rowOrderPreserved = 5;
			
			// aapt resource value: 3
			public const int GridLayout_useDefaultMargins = 3;
			
			public static int[] GridLayout_Layout = new int[] {
					16842996,
					16842997,
					16842998,
					16842999,
					16843000,
					16843001,
					16843002,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 1
			public const int GridLayout_Layout_android_layout_height = 1;
			
			// aapt resource value: 2
			public const int GridLayout_Layout_android_layout_margin = 2;
			
			// aapt resource value: 6
			public const int GridLayout_Layout_android_layout_marginBottom = 6;
			
			// aapt resource value: 3
			public const int GridLayout_Layout_android_layout_marginLeft = 3;
			
			// aapt resource value: 5
			public const int GridLayout_Layout_android_layout_marginRight = 5;
			
			// aapt resource value: 4
			public const int GridLayout_Layout_android_layout_marginTop = 4;
			
			// aapt resource value: 0
			public const int GridLayout_Layout_android_layout_width = 0;
			
			// aapt resource value: 10
			public const int GridLayout_Layout_layout_column = 10;
			
			// aapt resource value: 11
			public const int GridLayout_Layout_layout_columnSpan = 11;
			
			// aapt resource value: 12
			public const int GridLayout_Layout_layout_columnWeight = 12;
			
			// aapt resource value: 13
			public const int GridLayout_Layout_layout_gravity = 13;
			
			// aapt resource value: 7
			public const int GridLayout_Layout_layout_row = 7;
			
			// aapt resource value: 8
			public const int GridLayout_Layout_layout_rowSpan = 8;
			
			// aapt resource value: 9
			public const int GridLayout_Layout_layout_rowWeight = 9;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
